suricata:
    build: suricata
    volumes:
        - ./config/suricata/suricata.yaml:/etc/suricata/suricata.yaml:ro
        - ./data/suricata:/var/log/suricata:rw
        - ./data/scirius/:/etc/suricata/rules:rw
    privileged: true
    net: host
    command: --af-packet=wlan0
#    links:
#        - scirius

elasticsearch:
    image: elasticsearch
    volumes:
        - ./data/elasticsearch:/usr/share/elasticsearch/data:rw

logstash:
    image: logstash
    links:
        - elasticsearch
    command: -f /etc/logstash/logstash.conf
    volumes:
        - ./config/logstash:/etc/logstash:ro
        - ./data/suricata:/var/log/suricata:ro
    hostname: suricata

kibana:
    image: kibana
    ports:
     - 5601:5601
    links:
        - elasticsearch

scirius:
    build: scirius
    ports:
     - 8000:8000
    volumes:
        - ./config/scirius:/etc/scirius:ro
        - ./data/scirius:/etc/suricata/rules:rw
        - ./data/sciriusdata:/opt/selks/sciriusdata:rw
    links:
        - elasticsearch
        - kibana
